### 0. Importer les bibliothèques nécessaires 

**Déf :** 

-`NumPy est une bibliothèque open-source du langage Python conçue pour le calcul scientifique et numérique. Elle permet de manipuler facilement des tableaux et des matrices de données de grande taille (en une ou plusieurs dimensions), un peu comme une super-calculatrice mathématique ultra-rapide.`

-`Pandas est une bibliothèque open-source du langage Python conçue pour la manipulation et l'analyse de données. Elle permet de travailler facilement avec des données tabulaires (lignes et colonnes), un peu comme un tableau Excel ou une table SQL`

-`Matplotlib est une bibliothèque open-source du langage Python conçue pour la visualisation de données. Elle permet de créer facilement des graphiques clairs et personnalisés (courbes, histogrammes, nuages de points), un peu comme un crayon et une feuille de dessin pour illustrer vos chiffres.`

-`Scikit-learn est une bibliothèque open-source du langage Python conçue pour l'apprentissage automatique (machine learning). Elle permet d'entraîner facilement des modèles pour faire des prédictions ou classer des données, un peu comme une boîte à outils intelligente capable d'apprendre à partir d'exemples passés`

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

#### 0.1 Printer les versions

In [6]:
print("Version de Numpy :", np.__version__)
print("Version de Pandas :", pd.__version__)
print("Version de Matplotlib :", plt.matplotlib.__version__)
print("Version de Seaborn :", sns.__version__)
print("Version de Scikit-learn :", sklearn.__version__)

Version de Numpy : 2.4.4
Version de Pandas : 3.0.5
Version de Matplotlib : 3.11.1
Version de Seaborn : 0.13.2
Version de Scikit-learn : 1.9.0

### 1.1 : Chargement des données

La fonction `pd.read_csv()` permet de charger un fichier CSV dans un DataFrame Pandas.

Le fichier `smart_building_raw.csv` contient les données brutes provenant des capteurs des bâtiments intelligents.

Les données sont importées dans un DataFrame nommé `df`, qui sera utilisé pour toute la suite de l'atelier.

In [7]:
import pandas as pd

df = pd.read_csv("../data/smart_building_raw.csv")

df

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
0,1174,2025-02-13 06:00:00,B8,Entrepôt,A,23.0,40.0,851.0,26.0,138.4,Eco,Normal,Jeudi,Non
1,1275,2025-03-10 12:00:00,B7,Bureau,D,28.0,69.0,538.0,0.0,170.2,Eco,Normal,Lundi,Non
2,1493,2025-05-04 00:00:00,B5,Centre commercial,B,19.5,52.3,1198.0,64.0,149.8,Normal,Normal,Dimanche,Oui
3,1073,2025-01-19 00:00:00,B6,Université,D,20.0,58.4,1014.0,30.0,141.6,Normal,Normal,Dimanche,Non
4,1454,2025-04-24 06:00:00,B7,Bureau,D,26.8,70.5,628.0,42.0,228.3,Normal,Normal,Jeudi,Non
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
502,1107,2025-01-27 12:00:00,B2,École,C,29.8,66.5,778.0,48.0,243.5,Normal,Normal,Lundi,Non
503,1271,2025-03-09 12:00:00,B3,Hôpital,B,21.1,66.3,3900.0,53.0,145.8,Eco,Alerte,Dimanche,Oui
504,1349,2025-03-29 00:00:00,B5,Centre commercial,B,21.6,61.9,959.0,33.0,100.2,Eco,Normal,Samedi,Non
505,1436,2025-04-19 18:00:00,B7,Bureau,C,21.2,54.5,1066.0,38.0,150.9,Boost,Normal,Samedi,Oui
506,1103,2025-01-26 12:00:00,B2,École,D,NaN,64.8,584.0,29.0,163.4,Normal,Panne,Dimanche,Non

### 1.2 : Afficher les premières lignes

La méthode `head()` permet d'afficher les premières lignes d'un DataFrame.

Par défaut, elle affiche les 5 premières lignes.

Cette commande permet d'avoir un premier aperçu de la structure et du contenu des données.

In [8]:
df.head()

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
0,1174,2025-02-13 06:00:00,B8,Entrepôt,A,23.0,40.0,851.0,26.0,138.4,Eco,Normal,Jeudi,Non
1,1275,2025-03-10 12:00:00,B7,Bureau,D,28.0,69.0,538.0,0.0,170.2,Eco,Normal,Lundi,Non
2,1493,2025-05-04 00:00:00,B5,Centre commercial,B,19.5,52.3,1198.0,64.0,149.8,Normal,Normal,Dimanche,Oui
3,1073,2025-01-19 00:00:00,B6,Université,D,20.0,58.4,1014.0,30.0,141.6,Normal,Normal,Dimanche,Non
4,1454,2025-04-24 06:00:00,B7,Bureau,D,26.8,70.5,628.0,42.0,228.3,Normal,Normal,Jeudi,Non

### 1.3 : Afficher les dernières lignes

La méthode `tail()` permet d'afficher les dernières lignes d'un DataFrame.

Par défaut, elle affiche les 5 dernières lignes.

Cette observation permet de vérifier que le dataset est correctement chargé jusqu'à sa dernière observation.

In [9]:
df.tail()

,id_mesure,date,batiment,type_batiment,zone,temperature,humidite,co2,occupation,consommation_kwh,mode_climatisation,etat_systeme,jour_semaine,alerte
502,1107,2025-01-27 12:00:00,B2,École,C,29.8,66.5,778.0,48.0,243.5,Normal,Normal,Lundi,Non
503,1271,2025-03-09 12:00:00,B3,Hôpital,B,21.1,66.3,3900.0,53.0,145.8,Eco,Alerte,Dimanche,Oui
504,1349,2025-03-29 00:00:00,B5,Centre commercial,B,21.6,61.9,959.0,33.0,100.2,Eco,Normal,Samedi,Non
505,1436,2025-04-19 18:00:00,B7,Bureau,C,21.2,54.5,1066.0,38.0,150.9,Boost,Normal,Samedi,Oui
506,1103,2025-01-26 12:00:00,B2,École,D,NaN,64.8,584.0,29.0,163.4,Normal,Panne,Dimanche,Non

### 1.4 : Nombre d'observations

La propriété `shape` permet d'obtenir les dimensions d'un DataFrame.

Le premier élément correspond au nombre de lignes.

Chaque ligne représente une observation, c'est-à-dire une mesure enregistrée par les capteurs.

In [10]:
df.shape[0]

507

### 1.5 : Nombre de variables

Le deuxième élément de la propriété `shape` correspond au nombre de colonnes.

Chaque colonne représente une variable du dataset.

In [11]:
df.shape[1]

14

### 1.6 : Afficher les noms des variables

La propriété `columns`, combinée à `select_dtypes()`, permet d'afficher les noms de toutes les colonnes numériques du DataFrame.

In [12]:
df.select_dtypes(include="number").columns

Index(['id_mesure', 'temperature', 'humidite', 'co2', 'occupation',
       'consommation_kwh'],
      dtype='str')

#### notes sur les variables numériques

Les variables numériques sont les colonnes contenant des valeurs quantitatives.

À l'aide de la fonction `select_dtypes()`, les variables numériques suivantes ont été identifiées :

- `id_mesure`
- `temperature`
- `humidite`
- `co2`
- `occupation`
- `consommation_kwh`

La colonne `id_mesure` est numérique, mais elle correspond à un identifiant et ne sera pas considérée comme une variable quantitative pour les analyses statistiques et les corrélations.

### 1.7 : Noms des variables catégorielles

La propriété `.columns`, combinée à `select_dtypes()`, permet d'obtenir uniquement les noms des colonnes de type textuel (chaînes de caractères) du DataFrame.

In [13]:
df.select_dtypes(include="object").columns

C:\Users\Invite\AppData\Local\Temp\ipykernel_14008\1196084386.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object").columns

Index(['date', 'batiment', 'type_batiment', 'zone', 'mode_climatisation',
       'etat_systeme', 'jour_semaine', 'alerte'],
      dtype='str')

#### notes sur les variables catégorielles

Les variables catégorielles sont les colonnes contenant des valeurs représentant des catégories ou des groupes.

Les variables catégorielles identifiées sont :

- `batiment`
- `type_batiment`
- `zone`
- `mode_climatisation`
- `etat_systeme`
- `jour_semaine`
- `alerte`

La colonne `date` apparaît également parmi les variables de type `object`, mais elle semble correspondre à une variable temporelle stockée sous forme de texte. Elle sera vérifiée et convertie dans la question suivante.

### 8: Identifier les dates

L'objectif est d'identifier les variables contenant des dates ou des informations temporelles.

La colonne `date` a été détectée précédemment comme une variable de type `object`. Elle doit donc être vérifiée et convertie en format datetime afin de pouvoir être utilisée correctement dans les analyses temporelles.

In [14]:
df["date"].dtype

### 9: Identifier les identifiants

Un identifiant permet de reconnaître de manière unique une observation dans un dataset.

Dans les variables disponibles, `id_mesure` semble être un identifiant numérique. Il ne doit pas être considéré comme une variable quantitative pour calculer des statistiques ou des corrélations.

In [15]:
# Vérifier si id_mesure contient des valeurs uniques
df["id_mesure"].is_unique

False

#### notes

La colonne `id_mesure` est identifiée comme une variable d'identification(id).

Son rôle est de distinguer les différentes mesures. Même si elle contient des nombres, sa valeur n'a pas de signification statistique directe.

Elle sera donc exclue des analyses statistiques et des matrices de corrélation.

Aussi le fait qu'elle ne contient pas de valeurs uniques indique la présence de doublons

In [16]:
df["id_mesure"].duplicated().sum()

np.int64(7)

### 10: Déterminer les statistiques descriptives

Les statistiques descriptives permettent de résumer les principales caractéristiques des variables numériques.

Les indicateurs demandés sont :

- la moyenne ;
- la médiane ;
- le minimum ;
- le maximum ;
- l'écart-type ;
- les quartiles.

La variable `id_mesure` est exclue, car elle correspond à un identifiant et non à une mesure quantitative.

In [17]:
variables_numeriques = [
    "temperature",
    "humidite",
    "co2",
    "occupation",
    "consommation_kwh"
]

statistiques = pd.DataFrame({
    "moyenne": df[variables_numeriques].mean(),
    "mediane": df[variables_numeriques].median(),
    "minimum": df[variables_numeriques].min(),
    "maximum": df[variables_numeriques].max(),
    "ecart_type": df[variables_numeriques].std(),
    "q1": df[variables_numeriques].quantile(0.25),
    "q2": df[variables_numeriques].quantile(0.50),
    "q3": df[variables_numeriques].quantile(0.75)
})

statistiques

,moyenne,mediane,minimum,maximum,ecart_type,q1,q2,q3
temperature,24.154141,24.00,-30.0,96.0,7.418465,21.600,24.00,26.000
humidite,57.864113,57.55,-12.0,160.0,16.026336,49.275,57.55,65.750
co2,844.150000,787.50,89.0,6000.0,582.181386,623.750,787.50,952.000
occupation,44.850299,46.00,-20.0,116.0,24.949139,27.000,46.00,61.000
consommation_kwh,169.069323,169.80,-100.0,336.2,53.164294,136.875,169.80,202.975

#### notes sur les stats descriptives

- La moyenne représente la valeur moyenne des observations. = somme/ nbr
- La médiane représente la valeur centrale lorsque les données sont classées. = milieu
- Le minimum représente la plus petite valeur observée.
- Le maximum représente la plus grande valeur observée.
- L'écart-type mesure la dispersion des données autour de la moyenne.
- Q1 correspond au premier quartile : 25 % des valeurs lui sont inférieures ou égales.
- Q2 correspond à la médiane.
- Q3 correspond au troisième quartile : 75 % des valeurs lui sont inférieures ou égales.